cs_proj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('opeapp/', include('opeapp.urls')),
    path('admin/', admin.site.urls),
]

opeapp/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = 'opeapp'

urlpatterns = [
    path('', RedirectView.as_view(url='login/', permanent=False), name='index'),
    path('login/', views.login_view, name='login'),
    path('home/', views.home_view, name='home'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('students/', views.students_view, name='students'),
    path('student/<int:student_id>/', views.student_details, name='student_details'),
    path('courses/', views.courses_view, name='courses'),
    path('add_course_students/<int:course_id>/', views.add_course_students, name='add_course_students'),
    path('grades/', views.grades_view, name='grades'),
]

opeapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Student(models.Model):
    name = models.CharField(max_length=255)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name if self.name else ''
    
class Course(models.Model):
    name = models.CharField(max_length=255)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class CourseStudent(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    grade = models.IntegerField(null=True)  # Add "null=True" to make grade optional

    def __str__(self):
        return f"{self.course.name} - {self.student.name}"
    
    class Meta:
        unique_together = ('course', 'student')  # To create a composite unique constraint

opeapp/views.py
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from .models import Student, Course, CourseStudent
from django.db.models import Q
from django.db import connection

# Creating unsafe superuser within views. Comment out the function and its call:
def create_superuser():
    User = get_user_model()
    username = 'admin'
    email = 'admin@example.com'
    password = '1234'

    if not User.objects.filter(username=username).exists():
        user = User.objects.create_superuser(username, email, password)
        print(f"Superuser '{username}' created successfully.")
    else:
        print(f"Superuser '{username}' already exists.")

create_superuser()


@login_required
def home_view(request):
    context = {}
    return render(request, 'home.html', context)

def login_view(request):
    context = {}

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return render(request, 'home.html', context)
        else:
            messages.error(request, 'Invalid credentials. Please try again.')

    return render(request, 'login.html', context)

def signup_view(request):
    context = {}
    if request.method == 'POST':
        username = request.POST['username']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        User = get_user_model()
        if password1 != password2:
            messages.error(request, 'Passwords do not match.')
        elif User.objects.filter(username=username).exists():
            messages.error(request, 'Username already exists.')
        else:
            # Create a new user
            user = User.objects.create_user(username=username, password=password1)
            user.save()
            messages.success(request, 'Your account has been created. You can now log in.')
            return render(request, 'login.html', context)

    return render(request, 'signup.html', context)

@login_required
def logout_view(request):
    #logout(request)
    return render(request, 'login.html')

@login_required
def students_view(request):
    if request.method == "POST":
        student_name = request.POST.get('student_name')
        creator_id = request.user.id
        existing_student = Student.objects.filter(name=student_name, creator=creator_id).exists()

        if existing_student:
            messages.error(request, "A student with this name already exists.")
        else:
            new_student = Student(name=student_name, creator=request.user)
            new_student.save()
            messages.success(request, f"{student_name} added successfully.")

    # Fetch all students associated with the current user
    creator_id = request.user.id
    search_query = request.GET.get('search_query')

    if search_query:
        # Safe SQL query, uncomment the following line:
        # students = Student.objects.filter(Q(name__icontains=search_query) & Q(creator=creator_id))

        # Unsafe raw SQL query, comment out the whole with-statement:
        with connection.cursor() as cursor:
            query = "SELECT * FROM opeapp_student WHERE creator_id = " + str(creator_id) + " AND name LIKE '%" + search_query + "%'"
            cursor.execute(query)
            students_query = cursor.fetchall()
            students = [Student(id=student[0], name=student[1], creator_id=student[2]) for student in students_query]

    else:
        # If no search query, get all students for the current user
        students = Student.objects.filter(creator=creator_id)

    context = {
        'students': students
    }
    print('Creator_id: ', creator_id)
    return render(request, 'students.html', context)

@login_required
def courses_view(request):
    if request.method == "POST":
        course_name = request.POST.get('course_name')
        creator_id = request.user.id
        print('Course name: ', course_name, ' creator id: ', creator_id)
        existing_course = Course.objects.filter(name=course_name, creator=creator_id).exists()

        if existing_course:
            messages.error(request, "A course with this name already exists.")
        else:
            creator = request.user
            new_course = Course(name=course_name, creator=creator)
            print('new course: ', new_course)
            new_course.save()
            messages.success(request, f"{course_name} added successfully.")

    # Fetch all students associated with the current user
    creator_id = request.user.id
    courses = Course.objects.filter(creator=creator_id)

    context = {
        'courses': courses
    }
    print('Creator_id: ', creator_id)
    return render(request, 'courses.html', context)

@login_required
def add_course_students(request, course_id):
    if request.method == 'POST':
        student_ids = request.POST.getlist('student_ids')
        course = Course.objects.get(pk=course_id, creator_id=request.user)

        CourseStudent.objects.filter(course=course).delete()
        print('Student_ids: ', student_ids)
        for student_id in student_ids:
            student = Student.objects.get(pk=student_id)
            print('Student: ', student)
            CourseStudent.objects.create(course=course, student=student)

        messages.success(request, "Course students updated successfully.")
        courses = Course.objects.filter(creator=request.user.id)
        return render(request, 'courses.html', {'courses': courses})

    course = Course.objects.get(pk=course_id, creator_id=request.user)
    students = Student.objects.filter(creator_id=request.user)
    course_students = CourseStudent.objects.filter(course=course)
    associated_student_ids = [cs.student.id for cs in course_students]
    print('Associated student ids: ', associated_student_ids, course_students, course)
    context = {
        'course_name': course.name,
        'course_id': course.id,
        'students': students,
        'associated_student_ids': associated_student_ids,
    }

    return render(request, 'course.html', context)

@login_required
def grades_view(request):
    if request.method == 'POST':
        for key in request.POST:
            if key.startswith('grade-'):
                _, student_id, course_id = key.split('-')
                grade = request.POST[key]

                course_student = CourseStudent.objects.get(
                    course_id=int(course_id),
                    student_id=int(student_id)
                )
                course_student.grade = int(grade)
                course_student.save()
        messages.success(request, "Grades updated successfully.")

        # After updating grades, re-fetch the data and render the template
        courses = Course.objects.filter(creator=request.user)
        students_courses = {}

        for course in courses:
            associated_students = CourseStudent.objects.filter(course=course)
            student_data = []
            for student in associated_students:
                student_data.append({
                    'student_id': student.student.id,
                    'student_name': student.student.name,
                    'course_id': student.course.id,
                    'grade': student.grade,
                })

            students_courses[course.name] = {'students': student_data}

        context = {
            'courses': courses,
            'students_courses': students_courses,
        }
        return render(request, 'grades.html', context)
    
    # If it's a GET request, initially render the page with the course and student data
    courses = Course.objects.filter(creator=request.user)
    students_courses = {}

    for course in courses:
        associated_students = CourseStudent.objects.filter(course=course)
        student_data = []
        for student in associated_students:
            student_data.append({
                'student_id': student.student.id,
                'student_name': student.student.name,
                'course_id': student.course.id,
                'grade': student.grade,
            })

        students_courses[course.name] = {'students': student_data}

    context = {
        'courses': courses,
        'students_courses': students_courses,
    }
    return render(request, 'grades.html', context)

@login_required
def student_details(request, student_id):
    try:
        # Allow only users who have created this student:
        #student = Student.objects.get(pk=student_id, creator=request.user)

        # Broken Access Control - other users can view details by modifying URL in the browser:
        student = Student.objects.get(pk=student_id)
    except:
        messages.error(request, "You do not have permission to view this student's details.")
        return render(request, 'students.html')
    course_students = CourseStudent.objects.filter(student=student)
    student_courses = {}

    for course_student in course_students:
        course_name = course_student.course.name
        grade = course_student.grade

        student_courses[course_name] = {'grade': grade}

    context = {
        'student_name': student.name,
        'course_students': student_courses
    }

    return render(request, 'student.html', context)

opeapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OpeApu - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body>
    <header class="header">
        <h1>OpeApu</h1>
    </header>
    {% if user.is_authenticated %}
    <div>
        <nav>
            <ul>
                {% block link %}
                <li><a href="{% url 'opeapp:home' %}">Etusivu</a></li>
                <li><a href="{% url 'opeapp:students' %}">Oppilaat</a></li>
                <li><a href="{% url 'opeapp:courses' %}">Kurssit</a></li>
                <li><a href="{% url 'opeapp:grades' %}">Arvosanat</a></li>
                <li><a href="{% url 'opeapp:logout' %}">Kirjaudu ulos</a></li>
                {% endblock %}
            </ul>
        </nav>
    </div>
    {% endif %}
    <div id="messages">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="flash-message {% if message.tags %}{{ message.tags }}{% endif %}">
                        {{ message }}
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
    {% block content %}{% endblock %}
</body>
</html>

opeapp/templates/course.html
{% extends "base.html" %}
{% block title %}Lisää kurssin oppilaat{% endblock %}
{% block link %}
    {% if user.is_authenticated %}
        {{ block.super }}
    {% endif %}
{% endblock %}

{% block content %}
    <h2>{{ course_name }}</h2>
    <p>Lisää kurssin oppilaat:</p>
    <form action="{% url 'opeapp:add_course_students' course_id=course_id %}" method="POST">
        {% csrf_token %}
        <ul style="list-style-type: none;">
            {% for student in students %}
                <li>
                    <input type="checkbox" name="student_ids" value="{{ student.id }}"
                    {% if student.id in associated_student_ids %}
                        checked
                    {% endif %}
                    >
                    {{ student.name }}
                </li>
            {% endfor %}
        </ul>
        <button class="button-style" type="submit">Tallenna</button>
    </form>
{% endblock %}

opeapp/templates/courses.html
{% extends "base.html" %}
{% block title %}Kurssit{% endblock %}
{% block link %}
    {% if user.is_authenticated %}
        {{ block.super }}
    {% endif %}
{% endblock %}
{% block content %}
    <h2>Kurssit</h2>

    <div class="button-container">
        <button class="button-style" id="new-course-button">Lisää kurssi</button>
    </div>

    <div id="new-course-form" style="display: none;">
        <form action="{% url 'opeapp:courses' %}" method="POST">
            {# {% csrf_token %} #}
            <label for="course-name">Kurssin nimi:</label>
            <input type="text" id="course-name" name="course_name" required minlength="3" maxlength="20">
            <button class="button-style" type="submit" name="action" value="add_course">Tallenna</button>
            <button class="button-style" type="button" id="cancel-button">Peruuta</button>
        </form>
    </div>
    <br>
    <table class="student-table">
        <tbody>
            {% for course in courses %}
                <tr>
                    <td><span class="course-name">{{ course.name }}</span></td>
                    <td><a href="{% url 'opeapp:add_course_students' course.id %}"><button class="button-style">Näytä tiedot</button></a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <script>
        // JavaScript to show/hide the new course form
        document.getElementById("new-course-button").addEventListener("click", () => {
            document.getElementById("new-course-form").style.display = "block";
        });

        document.getElementById("cancel-button").addEventListener("click", () => {
            document.getElementById("new-course-form").style.display = "none";
        });
    </script>
{% endblock %}

opeapp/templates/grades.html
{% extends "base.html" %}
{% block title %}Arvosanat{% endblock %}
{% block link %}
    {% if user.is_authenticated %}
        {{ block.super }}
    {% endif %}
{% endblock %}
{% block content %}
    <h2>Arvosanat</h2>

    <form method="POST" action="{% url 'opeapp:grades' %}">
        {# {% csrf_token %} #}
        Valitse kurssi:
        <div class="selector">
            <select id="courseSelect" name="course">
                <option value="" selected disabled>Valitse kurssi</option>
                {% for course in courses %}
                    <option value="{{ course }}">{{ course }}</option>
                {% endfor %}
            </select>
        </div>
        <br><br>
        <h3 id="selectedCourseName"></h3>
        <table class="student-table" style="display: none;">
            <thead><tr>
                <th>Oppilas</th>
                <th>Anna arvosana</th>
                <th>Kurssin arvosana</th>
                <th style="display: none;">Kurssi ID</th>
            </thead></tr>
            {% for course_name, course_data in students_courses.items %}
                    {% for student_data in course_data.students %}
                        <tr data-course="{{ course_name }}">
                            <td>{{ student_data.student_name }}</td>
                            <td class="center-input">
                                <input
                                    type="number"
                                    name="grade-{{ student_data.student_id }}-{{ student_data.course_id }}"
                                    min="4"
                                    max="10"
                                    step="1"
                                    value="{% if student_data.grade is not none %}{{ student_data.grade }}{% else %}7{% endif %}"
                                    placeholder="4-10"
                                />
                            </td>
                            <td class="center-input">
                                {% if student_data.grade is none %}
                                    -
                                {% else %}
                                    {{ student_data.grade }}
                                {% endif %}
                            </td>
                            <td style="display: none;">
                                <input type="hidden" name="course_id-{{ student_data.student_id }}" value="{{ student_data.course_id }}" />
                                <input type="hidden" name="student_course-{{ student_data.student_id }}-{{ student_data.course_id }}" value="{{ course_name }}" />
                            </td>
                        </tr>
                    {% endfor %}
                
            {% endfor %}
        </table>
        <br>
        <button class="button-style" type="submit" style="display: none;">Tallenna</button>
    </form>

    <script>
        const courseSelect = document.getElementById("courseSelect");
        const selectedCourseName = document.getElementById("selectedCourseName");
        const table = document.querySelector("table");
        const submitButton = document.querySelector("button[type='submit']");

        courseSelect.addEventListener("change", () => {
            // Get selected option
            const selectedOption = courseSelect.options[courseSelect.selectedIndex];
            
            // Update course name element with selected course's name
            selectedCourseName.textContent = selectedOption.textContent;

            const selectedCourse = selectedOption.textContent;
            const tableRows = document.querySelectorAll("table tr");

            tableRows.forEach(row => {
                const dataCourse = row.getAttribute("data-course");
                if (dataCourse === selectedCourse || dataCourse === null) {
                    row.style.display = "table-row";
                } else {
                    row.style.display = "none";
                }
            });

            table.style.display = "table";
            submitButton.style.display = "block";
        });
    </script>
{% endblock %}

opeapp/templates/home.html
{% extends "base.html" %}
{% block title %}Etusivu{% endblock %}
{% block link %}
    {% if user.is_authenticated %}
        {{ block.super }}
    {% endif %}
{% endblock %}
{% block content %}
    <h2>Etusivu</h2>
    <p>
        <em>Oppilaat</em>-välilehdellä voi lisätä uusia oppilaita tietokantaan ja lisäksi annetaan 
        kaikki tietokantaan luodut oppilaat listana. Listasta pääsee myös yksittäisen oppilaan 
        kurssiarvosanatietoihin käsiksi. 
    </p>
    <p> 
        <em>Kurssit</em>-välilehdellä voi luoda uusia kursseja ja 
        kaikki luodut kurssit annetaan listana. Luotuun kurssiin voi lisätä kurssille 
        osallistuvat oppilaat.
    </p>
    <p>
        <em>Arvosanat</em>-välilehdellä voi antaa kurssin oppilaille kurssiarvosanan.
    </p>
{% endblock %}

opeapp/templates/index.html
{% extends "base.html" %}
{% block title %}Etusivu{% endblock %}
{% block link %}
    {% if session.username %}
        {{ block.super }}
    {% endif %}
{% endblock %}
{% block content %}
    {% if session.username %}
        <h2>Etusivu</h2>
        <p>
            <em>Oppilaat</em>-välilehdellä voi lisätä uusia oppilaita tietokantaan ja lisäksi annetaan 
            kaikki tietokantaan luodut oppilaat listana. Listasta pääsee myös yksittäisen oppilaan 
            kurssiarvosanatietoihin käsiksi. 
        </p><p> 
            <em>Kurssit</em>-välilehdellä voi luoda uusia kursseja ja 
            kaikki luodut kurssit annetaan listana. Luotuun kurssiin voi lisätä kurssille 
            osallistuvat oppilaat. Kurssin voi myös poistaa, jos sille ei osallistu yhtään oppilasta.
        </p><p>
            <em>Arvosanat</em>-välilehdellä voi antaa kurssin oppilaille kurssiarvosanan.
        </p>
    {% else %}
        <br>
        <h2>Kirjaudu sisään</h2>
        <div class="box">
            <form action="{% url 'login' %}" method="POST">
                {% csrf_token %}
                <div class="t-field">
                    <input type="text" required name="username">
                    <span></span>
                    <label>Käyttäjätunnus</label>
                </div>
                <div class="t-field">
                    <input type="password" required name="password">
                    <span></span>
                    <label>Salasana</label>
                </div>
                <input class="login-input" type="submit" value="Kirjaudu">
                <div class="signup">
                    Ei tunnusta? <a href="/signup">Rekisteröidy tästä</a>
                </div>
            </form>
        </div>
    {% endif %}
{% endblock %}

opeapp/templates/login.html
{% extends "base.html" %}
{% block title %}Kirjaudu sisään{% endblock %}
{% block content %}
    <br>
    <h2>Kirjaudu sisään</h2>
    <div class="box">
        <form action="{% url 'opeapp:login' %}" method="POST">
            {% csrf_token %}
            <div class="t-field">
                <input type="text" required name="username">
                <span></span>
                <label>Käyttäjätunnus</label>
            </div>
            <div class="t-field">
                <input type="password" required name="password">
                <span></span>
                <label>Salasana</label>
            </div>
            <input class="login-input" type="submit" value="Kirjaudu">
            <div class="signup">
                Ei tunnusta? <a href="{% url 'opeapp:signup' %}">Rekisteröidy tästä</a>
            </div>
        </form>
    </div>
{% endblock %}

opeapp/templates/signup.html
{% extends "base.html" %}
{% block title %}Rekisteröityminen{% endblock %}
{% block content %}
    <br>
    <h2>Rekisteröityminen</h2>
    <div class="box">
        <form action="{% url 'opeapp:signup' %}" method="POST">
            {% csrf_token %}
            <div class="t-field">
                <input type="text" required name="username" minlength="3" maxlength="30">
                <span></span>
                <label>Anna käyttäjätunnus</label>
            </div>
            <div class="t-field">
                <input type="password" required name="password1" minlength="3" maxlength="30">
                <span></span>
                <label>Anna salasana</label>
            </div>
            <div class="t-field">
                <input type="password" required name="password2" minlength="3" maxlength="30">
                <span></span>
                <label>Anna salasana uudelleen</label>
            </div>
                
            <input class="login-input" type="submit" value="Tallenna">
            <div class="signup">
                <a href="{% url 'opeapp:login' %}">Palaa kirjautumissivulle</a>
            </div>
        </form>
    </div>
{% endblock %}

opeapp/templates/student.html
{% extends "base.html" %}
{% block title %}Oppilas{% endblock %}
{% block link %}
    {% if user.is_authenticated %}
        {{ block.super }}
    {% endif %}
{% endblock %}

{% block content %}
    <h2>{{ student_name }}</h2>

    <h3>Oppilaan kurssit:</h3>
    {% for course, data in course_students.items %}
        <b>{{ course }}</b>, arvosana: <b>{{ data.grade }}</b>
        <br>
    {% endfor %}
{% endblock %}

opeapp/templates/students.html
{% extends "base.html" %}
{% block title %}Oppilaat{% endblock %}
{% block link %}
    {% if user.is_authenticated %}
        {{ block.super }}
    {% endif %}
{% endblock %}
{% block content %}
    <h2>Oppilaat</h2>

    <div class="button-container">
        <button class="button-style" id="new-student-button">Lisää oppilas</button>
    </div>

    <div id="new-student-form" style="display: none;">
        <form action="{% url 'opeapp:students' %}" method="POST">
            {# {% csrf_token %} #}
            <label for="student-name">Nimi:</label>
            <input type="text" id="student-name" name="student_name" required minlength="3" maxlength="25">
            <button class="button-style" type="submit" name="action" value="add_student">Tallenna</button>
            <button class="button-style" type="button" id="cancel-button">Peruuta</button>
        </form>
    </div>
    <br>
    <div id="search-form">
        <form action="{% url 'opeapp:students' %}" method="GET">
            {# {% csrf_token %} #}
            <input type="text" id="search-query" name="search_query" placeholder="Etsi oppilasta">
            <button class="button-style" type="submit" name="action" value="search">Hae</button>
        </form>
    </div>
    <br>
    <table class="student-table">
        <tbody>
            {% for student in students %}
                <tr>
                    <td><span class="student-name">{{ student.name }}</span></td>
                    <td><a href="{% url 'opeapp:student_details' student.id %}"><button class="button-style">Oppilaan tiedot</button></a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <script>
        // JavaScript to show/hide the new student form
        document.getElementById("new-student-button").addEventListener("click", () => {
            document.getElementById("new-student-form").style.display = "block";
        });

        document.getElementById("cancel-button").addEventListener("click", () => {
            document.getElementById("new-student-form").style.display = "none";
        });
    </script>
{% endblock %}